upload_max_filesize = 100M
post_max_size = 110M
memory_limit = 512M
max_execution_time = 120
max_input_time = 60
max_input_vars = 5000
date.timezone = Asia/Tashkent
expose_php = Off
display_errors = Off
log_errors = On
error_log = /var/log/php/error.log
realpath_cache_size = 4096K
realpath_cache_ttl = 600
